### ISSUE TITLE
NetworkCallback

### ISSUE THREAD

**Issue by bphd** [Kry9toN/Clash4Magisk#3]
msg: java.lang.IllegalArgumentException: NetworkCallback was not registered
stacktrace: java.lang.RuntimeException: Unable to destroy activity {krypton.tbsafetychecker/krypton.tbsafetychecker.main.MainActivity}: java.lang.IllegalArgumentException: NetworkCallback was not registered
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5903)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5935)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6220)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6135)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:80)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:60)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8594)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.IllegalArgumentException: NetworkCallback was not registered
	at android.net.ConnectivityManager.unregisterNetworkCallback(ConnectivityManager.java:5083)
	at ax1.f(SourceFile:11)
	at krypton.tbsafetychecker.main.MainActivity.onDestroy(SourceFile:9)
	at android.app.Activity.performDestroy(Activity.java:9269)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1567)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5890)
	... 16 more

**Comment by Kry9toN** [comment]
no context?

**Comment by bphd** [comment]
Not really because it just crash as is
